version: "3"
services:
  mongo:
    build: 
      context: .
      dockerfile: docker/mongo/Dockerfile
    environment:
      - MONGODB_DATABASE=stage
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
  node:
    build: 
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stage
      - PORT=4000
      - GRAPHQL_PORT=4001
      - SECRET_KEY=random secret string
      - UNSPLASH_AK=unsplash access key
      - UNSPLASH_SK=unsplash secret key
      - PIXABAY_AK=pixabay access key
      - STORYBLOCKS_PK=storyblocks public key
      - STORYBLOCKS_PRK=storyblocks private key
    entrypoint: /entrypoint.sh -d mongo:27017 -c 'yarn start';
    networks:
      - backend
networks:
  backend:
volumes:
  mongodata: 